### PR TITLE
test: Move from CDP to BiDi

### PR DESCRIPTION
**Pull request by martinpitt**
See https://github.com/cockpit-project/cockpit/pull/20832

Drop chrome-remote-interface NPM dependency.

Explicitly add a "glob" devDependency to follow suit with https://github.com/cockpit-project/cockpit/commit/680decc155a It was previously used implicitly through a transient dependency of something else, but our esbuild po-plugin uses it explicitly.

### CODE REVIEW

**Review by tomasmatus — APPROVED** [review]

**Review by allisonkarlitskaya — APPROVED** [review]
Well, that was straightforward.

**Comment by justin-stephenson** [comment]
Hi @martinpitt What about mentions of `chrome-remote-interface` in https://github.com/cockpit-project/starter-kit/blob/main/test/browser/run-test.sh ?

**Comment by martinpitt** [comment]
@justin-stephenson whoops, thanks! → #950

But good that I have you "on the line". This needs some action in c-session-recording, please see https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/PUY5X5DT37LLGZRKK6ZZ6T2EOXLQXYPQ/

**Comment by justin-stephenson** [comment]
> @justin-stephenson whoops, thanks! → #950
> 
> But good that I have you "on the line". This needs some action in c-session-recording, please see https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/PUY5X5DT37LLGZRKK6ZZ6T2EOXLQXYPQ/

I saw your mail - We will take care of it, thanks!

**Pull request merged**
