### PR TITLE
Add dark-theme-support

### LINKED ISSUE #610: Dark mode support by default
Starter kit needs to be updated to support dark mode by default.

https://github.com/cockpit-project/cockpit/issues/10189

### PR DESCRIPTION
**Pull request by shawly**
I used the COCKPIT_REPO_COMMIT from cockpit-podman and added the `cockpit-dark-theme` import.
This adds dark mode to starter-kit.

Fixes #610

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! This change is correct in principle, but bumping to the new cockpit lib breaks translations. This needs to be investigated (next week).

**Comment by shawly** [comment]
> Thanks! This change is correct in principle, but bumping to the new cockpit lib breaks translations. This needs to be investigated (next week).

Oh alright, it seemed to be working fine but I haven't tested the translations yet. As soon as I get to translating my module I might also investigate this at a later time if you haven't already by then.

**Comment by martinpitt** [comment]
This is almost surely fixed by https://github.com/cockpit-project/cockpit/commit/7ccc7961c35 , so I took the liberty to push to your branch. I bumped COCKPIT_REPO_COMMIT to 285 and slightly cleaned up the commit message.

**Review by martinpitt — APPROVED** [review]
Thank you! I just realized I pushed to your `main` branch, sorry about that! Can you please `reset --hard origin/main`?

**Comment by shawly** [comment]
> Thank you! I just realized I pushed to your `main` branch, sorry about that! Can you please `reset --hard origin/main`?

No worries, thanks for merging!

**Pull request merged**
