### PR TITLE
Optional sizzle

### PR DESCRIPTION
**Pull request by jelly**
Experiment to test https://github.com/cockpit-project/cockpit/pull/18888

### CODE REVIEW

**Comment by jelly** [comment]
Well this is silly, `ph_select` uses `window.Sizzle(sel)` so that hard breaks all tests making this not really easily optional.

**Comment by jelly** [comment]
Made it optional, obviously should break when one uses `:contains`.

**Comment by martinpitt** [comment]
Yes, that's what I meant in in https://github.com/cockpit-project/cockpit/pull/18888 -- I think `ph_select()` should just fall back to `document.querySelector()` if sizzle is not defined.

**Comment by jelly** [comment]
> Yes, that's what I meant in in [cockpit-project/cockpit#18888](https://github.com/cockpit-project/cockpit/pull/18888) -- I think `ph_select()` should just fall back to `document.querySelector()` if sizzle is not defined.

https://github.com/cockpit-project/cockpit/pull/18888/commits/2dfebf38364ccede287522dde9c4d371b0c9764c :+1:

**Comment by jelly** [comment]
After the Cockpit PR lands we can attempt to do this again :)

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/18896 landed, so this is unblocked now?

**Comment by jelly** [comment]
> [cockpit-project/cockpit#18896](https://github.com/cockpit-project/cockpit/pull/18896) landed, so this is unblocked now?

yes, rebased!

**Review by martinpitt — APPROVED** [review]
Yippie!

**Pull request merged**
