### PR TITLE
packit: Enable CentOS Stream 10 tests

### PR DESCRIPTION
**Pull request by martinpitt**
- [x] https://github.com/fedora-copr/copr/issues/3193
 - [ ] ~https://issues.redhat.com/browse/TFT-2557~ (transient network flake, unrelated)

### CODE REVIEW

**Comment by martinpitt** [comment]
@thrix @lbarcziova [TF 2024-02.1 release](https://docs.testing-farm.io/Testing%20Farm/0.1/releases/2024-02.1.html) announced "CentOS Stream 10 available on Public ranch", and the [C10s cloud images](https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/images/) are still being produced. But it seems packit doesn't actually trigger the build and tests?

**Comment by martinpitt** [comment]
Thanks @lbarcziova ! Subscribed and blocking on that.

**Comment by martinpitt** [comment]
As https://github.com/fedora-copr/copr/issues/3193 is fixed now, retrying. I do get pending c10s build/test statuses now, let's see how far they get!

**Comment by martinpitt** [comment]
First [c10s TF attempt](https://artifacts.dev.testing-farm.io/57de2678-be35-44e8-a3f4-11857a6a9265/) failed on the setup scripts, but booting itself worked. I filed https://issues.redhat.com/browse/TFT-2557 for that, continuing to block.

In the meantime, I'll build a c10s image in our own CI.

**Comment by martinpitt** [comment]
[That failure](https://artifacts.dev.testing-farm.io/c94eb87a-15af-48d9-aa4a-9ae55dcf0bd1/) is now something else entirely, see https://bugzilla.redhat.com/show_bug.cgi?id=2273078 . Adding workaround.

**Review by jelly — APPROVED** [review]

**Pull request merged**
